config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pinterested', root_path, class: 'navbar-brand'%>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About Me', home_about_path %></li>
        <% if user_signed_in? %>
          
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% else %>
          
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
        
        
        
        
        
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>My Name is Dave</p>

app/views/home/index.html.erb
<div class="jumbotron center">
    <h1>Welcome to my Pinterested App!</h1>
    
    <p>Pretty cool don't you think?</p>
    
    <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-default' %>
    <% else %>
        <%= link_to "Login", new_user_session_path,class: 'btn btn-default' %>
        <%= link_to "Join", new_user_registration_path,class: 'btn btn-primary' %>
    <% end %>
   
   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'home/header' %>



<div class="container">
  
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>